names: ['COTS']
nc: 1
train: /Users/bushra/Documents/STA2453/tensorflow-great-barrier-reef/images/train
val: /Users/bushra/Documents/STA2453/tensorflow-great-barrier-reef/images/val
test: /Users/bushra/Documents/STA2453/tensorflow-great-barrier-reef/images/test